Repository openshift/addon-operator, pull requests merged in 2022-05, with the labels that each got.

#188 refactor: new sub-reconciler for namespace reconciliation
  internal/controllers/addon/controller.go
  internal/controllers/addon/namespace_reconciler.go
  internal/controllers/addon/namespace_reconciler_test.go
  internal/controllers/addon/phase_delete_unwanted_namespaces.go
  internal/controllers/addon/phase_delete_unwanted_namespaces_test.go
  internal/controllers/addon/utils.go
Labels: approved, lgtm

#189 refactor: new sub-reconciler for OLM reconciliation
  internal/controllers/addon/controller.go
  internal/controllers/addon/olm_reconciler.go
  internal/controllers/addon/phase_ensure_addon_instance.go
  internal/controllers/addon/phase_ensure_catalogsource.go
  internal/controllers/addon/phase_ensure_catalogsource_test.go
  internal/controllers/addon/phase_ensure_operator_group.go
  internal/controllers/addon/phase_ensure_operator_group_test.go
  internal/controllers/addon/phase_ensure_subscription.go
  internal/controllers/addon/phase_ensure_subscription_test.go
  internal/controllers/addon/phase_observe_csv.go
  internal/controllers/addon/secret_reconciler.go
  internal/controllers/addon/secret_reconciler_test.go
  internal/controllers/addon/utils.go
Labels: approved, lgtm

#190 Refactor logger to be a part of context
  internal/controllers/addon/controller.go
  internal/controllers/addon/olm_reconciler.go
  internal/controllers/addon/phase_ensure_catalogsource.go
  internal/controllers/addon/phase_ensure_catalogsource_test.go
  internal/controllers/addon/phase_ensure_operator_group.go
  internal/controllers/addon/phase_ensure_operator_group_test.go
  internal/controllers/addon/secret_reconciler_test.go
  internal/controllers/context.go
Labels: approved, lgtm

#191 refactor: new sub-reconciler for monitoring federation
  internal/controllers/addon/controller.go
  internal/controllers/addon/monitoring_federation_reconciler.go
  internal/controllers/addon/monitoring_federation_reconciler_test.go
  internal/controllers/addon/phase_delete_unwanted_monitoring_federation.go
  internal/controllers/addon/phase_delete_unwanted_monitoring_federation_test.go
Labels: approved, lgtm

#194 Fixed the update of Namespace and PullSecretName in every iteration.
  internal/controllers/addon/utils.go
Labels: approved, lgtm, ok-to-test

#195 Container runtime auto detection
  go.mod
  go.sum
  magefile.go
Labels: approved, lgtm

#196 Unit test for function parseAddonInstallConfigForAdditionalCatalogSources
  internal/controllers/addon/utils_test.go
Labels: approved, lgtm, ok-to-test

#199 unit test for parse addon install config function
  internal/controllers/addon/utils_test.go
Labels: approved, lgtm, ok-to-test

#200 Added unit test for monitoring federation and additional catalogsources
  internal/controllers/addon/utils_test.go
Labels: lgtm, ok-to-test
