Repository openshift/addon-operator, pull requests merged in 2022-06, with the labels that each got.

#202 Unit test for validateAddon and validateSecretPropagation for weebhoks.
  internal/webhooks/webhook_test.go
Labels: approved, lgtm, ok-to-test

#204 prepare release 1.3.1
  VERSION
  config/olm/addon-operator.csv.tpl.yaml
  config/openshift/manifests/addon-operator.csv.yaml
Labels: approved

#201 [MTSRE-528] Fix serviceMonitor bearerTokenFile and make portName configurable.
  apis/addons/v1alpha1/addons_types.go
  config/deploy/addons.managed.openshift.io_addons.yaml
  config/openshift/manifests/addons.crd.yaml
  docs/api-reference/_index.md
  integration/monitoring_federation_test.go
  internal/controllers/addon/monitoring_federation_reconciler_test.go
  internal/controllers/addon/utils.go
Labels: approved, lgtm

#205 Added unit test for phase_ensure_subscription.go
  internal/controllers/addon/phase_ensure_subscription_test.go
Labels: approved, lgtm, ok-to-test

#206 `OWNERS` file cleanup
  OWNERS
Labels: approved, lgtm

#198 refactor: merge sub-reconcilers into a single slice of sub-reconcilers
  internal/controllers/addon/addon_instance_reconciler.go
  internal/controllers/addon/addon_instance_reconciler_test.go
  internal/controllers/addon/controller.go
  internal/controllers/addon/monitoring_federation_reconciler.go
  internal/controllers/addon/namespace_reconciler.go
  internal/controllers/addon/olm_reconciler.go
  internal/controllers/addon/secret_reconciler.go
Labels: approved, lgtm

#207 Update golangci-lint to support Go 1.18
  magefile.go
Labels: approved, lgtm

#210 refactor and change name of HasEqualControllerRef
  integration/resource_adoption_test.go
  internal/controllers/addon/monitoring_federation_reconciler.go
  internal/controllers/addon/namespace_reconciler.go
  internal/controllers/addon/phase_ensure_catalogsource.go
  internal/controllers/addon/phase_ensure_catalogsource_networkpolicy.go
  internal/controllers/addon/phase_ensure_operator_group.go
  internal/controllers/addon/phase_ensure_subscription.go
  internal/controllers/common_utils.go
  internal/controllers/common_utils_test.go
Labels: approved, lgtm

#213 [Hypershift] Leader Election to use ADDON_OPERATOR_NAMESPACE
  cmd/addon-operator-manager/main.go
Labels: approved, lgtm

#208 Remove adoption runtime configuration CatalogSource and Subscription
  internal/controllers/addon/phase_ensure_catalogsource.go
  internal/controllers/addon/phase_ensure_catalogsource_test.go
  internal/controllers/addon/phase_ensure_subscription.go
  internal/controllers/addon/phase_ensure_subscription_test.go
  internal/testutil/fixtures.go
Labels: approved, lgtm

#215 Added better code readability
  internal/webhooks/webhook_test.go
Labels: approved, lgtm, ok-to-test

#216 Some nit fixes to redundant assignment
  internal/controllers/addon/utils.go
Labels: approved, lgtm, ok-to-test

#209 added unit-test for getDestinationSecretWithoutNamespace function
  internal/controllers/addon/secret_reconciler_test.go
Labels: approved, lgtm, ok-to-test

#217 Added mock unit test for phase_observe_csv.go
  internal/controllers/addon/phase_observe_csv_test.go
  internal/testutil/matchers.go
Labels: approved, lgtm, ok-to-test

#220 catalogsource object and subscription object name change
  integration/addon_test.go
  integration/broken_subscription_test.go
  integration/fixtures_test.go
  integration/resource_adoption_test.go
  internal/controllers/addon/phase_ensure_catalogsource.go
  internal/controllers/addon/phase_ensure_subscription.go
  internal/controllers/addon/utils.go
Labels: approved, lgtm

#221 release version 1.4.0
  VERSION
  config/olm/addon-operator.csv.tpl.yaml
  config/openshift/manifests/addon-operator.csv.yaml
Labels: approved, lgtm

#222 Add release and deployment instructions
  README.md
Labels: approved, lgtm

#223 nit: fix typo in function name
  internal/controllers/addon/utils_test.go
Labels: approved, lgtm, ok-to-test

#224 doc-fix: Updated README
  README.md
Labels: approved, lgtm, ok-to-test
