Repository openshift/addon-operator, pull requests merged in 2023-11, with the labels that each got.

#471 MTSRE-1521: Collect metrics for reconcile errors
  cmd/addon-operator-manager/main.go
  internal/controllers/addon/addon_deletion_reconciler.go
  internal/controllers/addon/addon_instance_reconciler.go
  internal/controllers/addon/addon_reconciler_options.go
  internal/controllers/addon/controller.go
  internal/controllers/addon/controller_test.go
  internal/controllers/addon/monitoring_federation_reconciler.go
  internal/controllers/addon/monitoring_stack_reconciler.go
  internal/controllers/addon/namespace_reconciler.go
  internal/controllers/addon/olm_reconciler.go
  internal/controllers/addon/package_operator_reconciler.go
  internal/controllers/addon/secret_reconciler.go
  internal/controllers/addoninstance/controller.go
  internal/controllers/addoninstance/options.go
  internal/controllers/addonoperator/controller.go
  internal/controllers/errors.go
  internal/metrics/recorder.go
  internal/metrics/recorder_test.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#480 Refine ADO magefile
  magefile.go
  magefiles/build.go
  magefiles/common.go
  magefiles/config.go
  magefiles/dependency.go
  magefiles/development.go
  magefiles/generate.go
  magefiles/release.go
  magefiles/test.go
Labels: approved, tide/merge-method-squash, lgtm

#490 prepare ado v1.14.0
  VERSION
  config/olm/addon-operator.csv.tpl.yaml
  config/openshift/manifests/addon-operator.csv.yaml
Labels: approved, lgtm

#495 Post migration refactor
  .gitignore
  Makefile
  deploy-extras/docker/addon-operator-bundle.Dockerfile
  deploy-extras/olm/addon-operator.csv.yaml
  deploy-extras/olm/trusted_ca_bundle_configmap.yaml
  deploy-extras/package/hcp/metrics.service.yaml
  deploy/10_serviceaccount.yaml
  deploy/15_clusterrole.yaml
  deploy/20_clusterrolebinding.yaml
  deploy/25_role.yaml
  deploy/30_rolebinding.yaml
  deploy/35_prometheus-role.yaml
  deploy/40_prometheus-rolebinding.yaml
  deploy/45_metrics-service.yaml
  deploy/50_servicemonitor.yaml
  deploy/55_trusted_ca_bundle_configmap.yaml
  deploy/60_deployment.yaml
  magefiles/build.go
  magefiles/development.go
Labels: approved

#496 fix: Remove redundant yaml split in CRDs
  deploy/crds/addons.managed.openshift.io_addoninstances.yaml
  deploy/crds/addons.managed.openshift.io_addonoperators.yaml
  deploy/crds/addons.managed.openshift.io_addons.yaml
Labels: approved, lgtm

#497 fix: Temporarily disable make-generate pre-commit check
  .pre-commit-config.yaml
Labels: approved, lgtm

#498 fix: Update ADO CSV per Operator SDK v1
  Makefile
  deploy-extras/docker/addon-operator-bundle.Dockerfile
  deploy-extras/olm/addon-operator.csv.tpl.yaml
  deploy-extras/olm/addon-operator.csv.yaml
  deploy-extras/olm/annotations.yaml
  magefiles/test.go
Labels: approved, lgtm

#499 fix: webhooks local deployment
  deploy-extras/webhook/00-tls-secret.yaml
  deploy-extras/webhook/deployment.yaml
  deploy-extras/webhook/service.yaml
  deploy-extras/webhook/validatingwebhookconfig.yaml
  magefiles/development.go
Labels: approved, lgtm

#504 Ensure Addon Operator Makefile targets has no conflicts with the golang-osd-operator convention's Makefile targets
  .pre-commit-config.yaml
  Makefile
Labels: approved, tide/merge-method-squash, lgtm

#494 MTSRE-841: Collect ocm client request reconcile error,
  cmd/api-mock/main.go
  controllers/addon/addon_controller.go
  controllers/errors.go
  go.mod
  go.sum
  integration/metrics_collection_test.go
  magefiles/development.go
Labels: approved, lgtm, jira/valid-reference

#507 MTSRE-1628: Ignore unclassified/undefined reconcile errors from metri…
  controllers/addon/addon_controller_test.go
  controllers/errors.go
  internal/metrics/recorder.go
  internal/metrics/recorder_test.go
Labels: approved, lgtm, jira/valid-reference

#505 ADO: Selectively report to addon upgrade policy endpoint
  controllers/addon/addon_controller.go
  controllers/addon/addon_controller_test.go
  controllers/addon/upgradepolicy_status.go
  controllers/addon/upgradepolicy_status_test.go
  deploy-extras/olm/addon-operator.csv.tpl.yaml
  deploy-extras/olm/addon-operator.csv.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  magefiles/development.go
  magefiles/test.go
  main.go
  options.go
Labels: approved, lgtm
