Repository openshift/addon-operator, pull requests merged in 2023-12, with the labels that each got.

#512 Boilerplate: Update to 25553e37bb43f4fa78e52d97dd394a63c72d9978
  .pre-commit-config.yaml
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/subscriber-report
  boilerplate/openshift/golang-osd-operator/app-sre.md
  boilerplate/openshift/golang-osd-operator/configure-fips.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/common-generate-operator-bundle.py
  boilerplate/openshift/golang-osd-operator/csv-generate/common.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.mk
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#509 Refactor ADO package build and deployment
  Makefile
  magefiles/build.go
Labels: approved, lgtm

#515 Deprecate metrics-relay-server from ADO package
  Makefile
  deploy-extras/package/hcp/addon-operator.yaml
  hack/build-deploy.sh
  hack/build-package.sh
Labels: approved, lgtm

#516 Add build-push package target
  Makefile
Labels: approved

#517 fix: package path for build target
  Makefile
  hack/build-deploy.sh
Labels: approved, lgtm

#518 Make ADO CSV generation dynamic
  .pre-commit-config.yaml
  Makefile
  bundle.Dockerfile
  bundle/manifests/addon-operator-metrics_v1_service.yaml
  bundle/manifests/addon-operator-servicemonitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/addon-operator.clusterserviceversion.yaml
  bundle/manifests/addons.managed.openshift.io_addoninstances.yaml
  bundle/manifests/addons.managed.openshift.io_addonoperators.yaml
  bundle/manifests/addons.managed.openshift.io_addons.yaml
  bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/trusted-ca-bundle_v1_configmap.yaml
  bundle/metadata/annotations.yaml
  hack/operator-sdk-run.sh
  magefiles/dependency.go
Labels: approved, lgtm

#523 Mtsre 1662 - Patch Webhookdefinition using Mage function
  Makefile
  bundle/manifests/addon-operator.clusterserviceversion.yaml
  hack/webhookdefinition.yaml
  magefiles/test.go
Labels: approved, tide/merge-method-squash, lgtm

#526 add Upgrade policy env variable in patch function of mage
  .pre-commit-config.yaml
  Makefile
  bundle/manifests/addon-operator.clusterserviceversion.yaml
  hack/operator-sdk-run.sh
  magefiles/test.go
Labels: approved, lgtm

#524 MTSRE-1644: Post BP Cleanup
  .github/dependabot.yml
  Makefile
  VERSION
  api/v1alpha1/zz_generated.openapi.go
  deploy-extras/development/webhook/00-tls-secret.yaml
  deploy-extras/development/webhook/service.yaml
  deploy-extras/development/webhook/validatingwebhookconfig.yaml
  deploy-extras/docker/addon-operator-bundle.Dockerfile
  deploy-extras/docker/addon-operator-manager.Dockerfile
  deploy-extras/docker/addon-operator-webhook.Dockerfile
  deploy-extras/docker/app-interface-push-images.Dockerfile
  deploy-extras/olm/addon-operator.csv.tpl.yaml
  deploy-extras/olm/addon-operator.csv.yaml
  deploy-extras/olm/annotations.yaml
  deploy/crds/addons.managed.openshift.io_addoninstances.yaml
  deploy/crds/addons.managed.openshift.io_addonoperators.yaml
  deploy/crds/addons.managed.openshift.io_addons.yaml
  go.mod
  magefiles/build.go
  magefiles/dependency.go
  magefiles/development.go
  magefiles/generate.go
  magefiles/release.go
  magefiles/test.go
Labels: approved, lgtm, jira/valid-reference

#521 use podscheduled reason for addon health info
  bundle/manifests/addon-operator.clusterserviceversion.yaml
  controllers/addon/addon_controller.go
  controllers/addon/addon_controller_test.go
  deploy/15_clusterrole.yaml
  internal/metrics/metrics_test.go
  internal/metrics/recorder.go
Labels: approved, lgtm

#525 [MTSRE-1664] Fix Addon Operator package deployment - Phase I
  Makefile
  deploy-extras/package/addon-operator-package.Containerfile
  hack/hypershift/package/addon-operator-package.Containerfile
  hack/hypershift/package/addon-operator.yaml
  hack/hypershift/package/addons.managed.openshift.io_addoninstances.yaml
  hack/hypershift/package/addons.managed.openshift.io_addonoperators.yaml
  hack/hypershift/package/addons.managed.openshift.io_addons.yaml
  hack/hypershift/package/manifest.yaml
  hack/hypershift/package/metrics.service.yaml
  hack/hypershift/package/namespace.yaml
  magefiles/build.go
Labels: approved, lgtm

#529 Auto patch ADO package deployment image
  Makefile
  hack/hypershift/README.md
  hack/hypershift/package/addon-operator-package.Containerfile
  hack/hypershift/package/addon-operator.yaml
  hack/hypershift/package/hc/addons.managed.openshift.io_addoninstances.yaml
  hack/hypershift/package/hc/addons.managed.openshift.io_addonoperators.yaml
  hack/hypershift/package/hc/addons.managed.openshift.io_addons.yaml
  hack/hypershift/package/hc/namespace.yaml
  hack/hypershift/package/hcp/addon-operator.yaml
  hack/hypershift/package/hcp/metrics.service.yaml
Labels: approved, lgtm

#530 Launch container process in privileged mode
  Makefile
Labels: approved, lgtm
